version: "3.8"
services:
  broker_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'broker_rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
        - next_basket_rabbitmq_net

networks:
  next_basket_rabbitmq_net:
    name: next_basket_rabbitmq_net
    driver: bridge